services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - API_KEY=${API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - PYTHONPATH=/app
      - TRANSFORMERS_CACHE=/tmp/huggingface_cache
      - MPLCONFIGDIR=/tmp/matplotlib
    command: gunicorn -b :8000 app.app:app --workers 1 --timeout 120

    env_file:
      - .env
    volumes:
      - ./analytics:/app/analytics
    networks:
      - flask_network

networks:
  flask_network: